# Scalars (Rank 0 Tensors) in Basic Python
1. List item
2. List item

In [1]:
x = 25


In [ ]:
x

25

In [2]:
type(x)

int

In [6]:
x_float = 25.0

In [ ]:
x_float

25.0

In [9]:
type(x_float)

float

# Scalars in PyTorch

In [10]:
import torch

In [13]:
x_pt = torch.tensor(25)

In [14]:
x_pt

tensor(25)

In [15]:
x_pt.shape

torch.Size([])

In [16]:
x_pt = torch.tensor(25, dtype = torch.float16)

In [17]:
x_pt

tensor(25., dtype=torch.float16)

In [18]:
x_pt = torch.tensor(25.0)

In [19]:
x_pt

tensor(25.)

In [20]:
x_pt.dtype

torch.float32

In [24]:
x_pt = torch.tensor(25,dtype = torch.int8)

In [25]:
x_pt

tensor(25, dtype=torch.int8)

In [ ]:
x_pt = torch.tensor(25, dtype = torch.int)

In [26]:
x_pt  

tensor(25, dtype=torch.int8)

# Scalars in TensorFlow

In [29]:
import tensorflow as tf

In [33]:
x_tf = tf.Variable(25, dtype = tf.int16)

In [34]:
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

In [35]:
x_tf.shape

TensorShape([])

In [37]:
y_tf = tf.Variable(3,dtype = tf.int16)

In [ ]:
y_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=3>

In [39]:
tf_sum1 = x_tf + y_tf

In [40]:
tf_sum1

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [42]:
tf_sum2 = tf.add(x_tf,y_tf)

In [45]:
tf_sum2

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [47]:
tf_sum2.numpy()

28

##Vectors

## Vectors as Numpy ndarray objects

In [92]:
import numpy as np


In [93]:
x = np.array([25,2,5])

In [94]:
x

array([25,  2,  5])

In [95]:
x.shape

(3,)

In [96]:
np.ndim(x)

1

In [97]:
type(x)

numpy.ndarray

In [98]:
x[0]

25

In [99]:
type(x[0])

numpy.int64

## Vector Transposition

In [67]:
X_T =x.T

In [70]:
X_T 

array([25,  2,  5])

In [71]:
x

array([25,  2,  5])

In [82]:
y= np.array([[25,2,5]])

In [83]:
y.shape

(1, 3)

In [84]:
y_t=y.T

In [85]:
y_t

array([[25],
       [ 2],
       [ 5]])

In [87]:
y_t.shape

(3, 1)

In [90]:
y_T = y.T

In [91]:
y_T

array([[25],
       [ 2],
       [ 5]])

## Norms

### L2 Norm (Euclidean Distance)

In [101]:
(25**2 + 2**2 + 5**2) ** (1/2)

25.573423705088842

In [102]:
np.linalg.norm(x)

25.573423705088842

### L1 Norm (Manhattan Distance)

In [104]:
np.abs(25) + np.abs(2) + np.abs(5)

32

### Squred L2 Norm

In [105]:
(25**2 + 2**2 + 5**2) 

654

### Max Norm

In [106]:
np.max([np.abs(25), np.abs(2), np.abs(5)])

25

### Dot Product of a Vector

In [108]:
x

array([25,  2,  5])

In [109]:
y = np.array([2,3,4])

In [110]:
np.dot(x,y)

76